#!/bin/bash
echo "#!/bin/bash" > 0-current_working_directory
echo "pwd" >> 0-current_working_directory
chmod 755 0-current_working_directory

echo "#!/bin/bash" > 1-listit
echo "ls" >> 1-listit
chmod 755 1-listit

echo "#!/bin/bash" > 2-bring_me_home
echo "cd" >> 2-bring_me_home
chmod 755 2-bring_me_home

echo "#!/bin/bash" > 3-lifetfiles
echo "ls -l" >> 3-listfiles
chmod 755 3-lifetfiles

echo "#!/bin/bash" > 4-listmorefiles
echo "ls -la" >> 4-listmorefiles
chmod 755 4-listmorefiles

echo "#!/bin/bash" > 5-listfilesdigitonly
echo "ls -aln" >> 5-listfilesdigitonly
chmod 755 5-listfilesdigitonly

echo "#!/bin/bash" > 6-firstdirectory
echo "mkdir /tmp/my_first_directory" >> 6-firstdirectory
chmod 755 6-firstdirectory

echo "#!/bin/bash" > 7-movethatfile
echo "mv /tmp/betty /tmp/my_first_directory" >> 7-movethatfile
chmod 755 7-movethatfile

echo "#!/bin/bash" > 8-firstdelete
echo "rm /tmp/my_first_directory/betty" >> 8-firstdelete
chmod 755 8-firstdelete

echo "#!/bin/bash" > 9-firstdirdeletion
echo "rm -r /tmp/my_first_directory" >> 9-firstdirdeletion
chmod 755 9-firstdirdeletion

echo "#!/bin/bash" > 10-back
echo "cd -" >> 10-back
chmod 755 10-back

echo "#!/bin/bash" > 11-lists
echo "ls -al . .. /boot" >> 11-lists
chmod 755 11-lists

echo "#!/bin/bash" > 12-file_type
echo "file /tmp/iamafile" >> 12-file_type
chmod 755 12-file_type

echo "#!/bin/bash" > 13-symbolic_link
echo "ln -s /bin/ls __ls__" >> 13-symbolic_link
chmod 755 13-symbolic_link

echo "#!/bin/bash" > 14-copy_html
echo "cp -u *.html .." >> 14-copy_html
chmod 755 14-copy_html

echo "#!/bin/bash" > 100-lets_move
echo "mv [[:upper:]]* /tmp/u" >> 100-lets_move
chmod 755 100-lets_move

echo "#!/bin/bash" > 101-clean_emacs
echo "" >> 101rm *~-clean_emacs
chmod 755 101-clean_emacs

echo "#!/bin/bash" > 102-tree
echo "mkdir -p welcome{,/to{,/school}}" >> 102-tree
chmod 755 102-tree





